name: 'dbt_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_project:    
    stage:
      northwind:
        schema: stage
        +materialized: table
      erp_new_system:
        schema: stage
        +materialized: table
    
    intermediate:
      schema: intermediate
      +materialized: ephemeral
      +docs:
        node_color: "#c0c0c0"
    
    datamart:
      schema: marts
      +materialized: table
      +docs:
        node_color: "#e6b530"

seeds:
  dbt_project:
    erp_northwind:
      schema: raw_northwind
    
    erp_new_system:
      schema: raw_erp_new_system

snapshots:
  dbt_project:
    northwind:
      schema: stage_northwind