models:
  - name: stg_new_address
    description: "Address of our customers and others. Example: Ana Silva, 123 Main Street"
    columns:
      - name: address_id
        data_type: string
        description: "Primary key of the address. Value composed as 'erp_new_system||' + original address_id."

      - name: ship_name
        data_type: string
        description: "Name of the shipping location."

      - name: ship_address
        data_type: string
        description: "Street address of the shipping location."

      - name: ship_city
        data_type: string
        description: "City of the shipping location."

      - name: ship_region
        data_type: string
        description: "Region or state of the shipping location. E.g.: IL, NY, MA, etc."

      - name: ship_postal_code
        data_type: string
        description: "Postal code of the shipping location."

      - name: ship_country
        data_type: string
        description: "Country of the shipping location."
  - name: stg_new_categories
    description: ""
    columns:
      - name: category_id
        data_type: string
        description: "Primary key of the category. Value composed as 'erp_new_system||' + original category_id."

      - name: category_name
        data_type: string
        description: "Name of the product category."

  - name: stg_new_customers
    description: ""
    columns:
      - name: customer_id
        data_type: string
        description: "Primary key of the customer. Value composed as 'erp_new_system||' + original customer_id."

      - name: company_name
        data_type: string
        description: "Name of the customer's company."

      - name: contact_name
        data_type: string
        description: "Main contact person at the customer."

  - name: stg_new_employee_hierarchy
    description: ""
    columns:
      - name: employee_id
        data_type: string
        description: "Primary key of the employee. Value composed as 'erp_new_system||' + original employee_id."

      - name: boss_id
        data_type: string
        description: "Foreign key to the immediate boss. Value composed as 'erp_new_system||' + original boss_id. Recursive relationship with employee_id."

      - name: employee_name
        data_type: string
        description: "Full name of the employee."

      - name: hierarchy_path
        data_type: string
        description: "Hierarchical path from the top to this employee. E.g.: Nancy Davolio -> Andrew Fuller -> Janet Leverling."

      - name: hierarchy_level
        data_type: int64
        description: "Hierarchy level of the employee. E.g.: 1 for top level, 2 for next, etc."

  - name: stg_new_employees
    description: ""
    columns:
      - name: employee_id
        data_type: string
        description: "Primary key of the employee. Value composed as 'erp_new_system||' + original employee_id."

      - name: name
        data_type: string
        description: "Name of the employee."

      - name: title
        data_type: string
        description: "Job title of the employee."

      - name: boss_id
        data_type: int64
        description: "Foreign key to the immediate boss (employee_id)."

  - name: stg_new_products
    description: ""
    columns:
      - name: product_id
        data_type: string
        description: "Primary key of the product. Value composed as 'erp_new_system||' + original product_id."

      - name: name
        data_type: string
        description: "Name of the product."

      - name: category_id
        data_type: string
        description: "Foreign key to the product category. Value composed as 'erp_new_system||' + original category_id."

      - name: supplier_id
        data_type: string
        description: "Foreign key to the supplier. Value composed as 'erp_new_system||' + original supplier_id."

  - name: stg_new_sales_details
    description: ""
    columns:
      - name: sale_id
        data_type: string
        description: "Primary key of the sale. Value composed as 'erp_new_system||' + original sale_id."

      - name: product_id
        data_type: string
        description: "Foreign key to the product. Value composed as 'erp_new_system||' + original product_id."

      - name: price_per_unit
        data_type: float64
        description: "Unit price of the product in the sale."

      - name: qty
        data_type: int64
        description: "Quantity of products sold."

      - name: discount_percentage
        data_type: float64
        description: "Discount percentage applied to the sale."

      - name: deleted
        data_type: boolean
        description: "Indicates if the record was deleted (soft delete)."

  - name: stg_new_sales
    description: ""
    columns:
      - name: sale_id
        data_type: string
        description: "Primary key of the sale. Value composed as 'erp_new_system||' + original sale_id."

      - name: customer_id
        data_type: string
        description: "Foreign key to the customer. Value composed as 'erp_new_system||' + original customer_id."

      - name: salesperson_id
        data_type: string
        description: "Foreign key to the salesperson. Value composed as 'erp_new_system||' + original salesperson_id."

      - name: ship_address_id
        data_type: string
        description: "Foreign key to the shipping address. Value composed as 'erp_new_system||' + original ship_address_id."

      - name: sale_date
        data_type: date
        description: "Date when the sale occurred."

      - name: freight_value
        data_type: float64
        description: "Freight value for the sale."

      - name: required_delivery_date
        data_type: date
        description: "Date requested for delivery by the customer."

      - name: shipped_date
        data_type: date
        description: "Date when the order was shipped."

      - name: shipped_flag
        data_type: string
        description: "Indicates if the order was shipped."

      - name: delayed_flag
        data_type: string
        description: "Indicates if the order was delivered late."

      - name: delayed_days
        data_type: int64
        description: "Number of days the delivery was delayed."

      - name: shipping_time
        data_type: int64
        description: "Total shipping time in days."

      - name: ship_via
        data_type: string
        description: "Shipping company or method used for delivery."

  - name: stg_new_suppliers
    description: ""
    columns:
      - name: supplier_id
        data_type: string
        description: "Primary key of the supplier. Value composed as 'erp_new_system||' + original supplier_id."

      - name: supplier_name
        data_type: string
        description: "Name of the supplier."

      - name: contact_person
        data_type: string
        description: "Main contact person at the supplier."

      - name: phone
        data_type: string
        description: "Supplier's contact phone number."

      - name: email
        data_type: string
        description: "Supplier's contact email address."