version: 2

sources:
  - name: erp_new_system
    description: "New system of sales"
    schema: dbt_raw_erp_new_system
    loader: bigquery
    tables:
      - name: new_address
        description: "Address of our customers and others. Example: Ana Silva, 123 Main Street"
        columns:
          - name: address_id
            description: "Primary key of the address"
            tests:
              - unique
              - not_null
          - name: ship_name
            description: "Name of the ship place"
          - name: ship_address
            description: "Number and Name of the street"
          - name: ship_city
            description: "City of the ship place"
          - name: ship_region
            description: "Region of the ship place. Ex.: IL, NY, MA, etc."
          - name: ship_postal_code
            description: "Postal code of the ship place"
          - name: ship_country
            description: "Country of the ship place"

      - name: new_categories
        description: "Categories of the products. Example: Eletrônicos, Periféricos de Computador, etc."
        columns:
          - name: category_id
            description: "Primary key of the category"
            tests:
              - unique
              - not_null
          - name: name
            description: "Name of the category"

      - name: new_customers
        description: "Customers of the new system. Example: Central Market, Hot Bread Bakery."
        columns:
          - name: customer_id
            description: "Primary key of the customer"
            tests:
              - unique
              - not_null
          - name: company_name
            description: "Name of the company"
          - name: contact_name
            description: "Name of the contact person"

      - name: new_employees
        description: "Employ of the company. Example: John Smith, Mary Johnson, etc."
        columns:
          - name: employee_id
            description: "Primary key of the employee"
            tests:
              - unique
              - not_null
          - name: name
            description: "Name of the employee"
          - name: title
            description: "Title of the employee. e.g.: Sales Manager, Junior Sales Analyst, etc."
          - name: boss_id
            description: "Id of the boss of the employee. This is related to employee_id at this table (recursive relationship)"

      - name: new_products
        description: "Products of the company. Example: Laptop, Printer, etc."
        columns:
          - name: product_id
            description: "Primary key of the product"
            tests:
              - unique
              - not_null
          - name: name
            description: "Name of the product"
          - name: category_id
            description: "Foreign key of the category (new_categories)"
          - name : supplier_id
            description: "Foreign key of the supplier (new_suppliers)"
          
      - name: new_sales
        description: ""
        columns:
          - name: sale_id
            description: "Primary key of the sale"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Foreign key of the customer (new_customers)"
            tests:
              - not_null
          - name: salesperson_id
            description: "Responsible salesperson of the sale"
          - name: sale_date
            description: "Date of the sale"
          - name: required_delivery_date
            description: "Required delivery date of the sale"
          - name: shipped_date
            description: "Shipped date of the sale"
          - name: ship_via
            description: "Company responsible to transport the products. e.g.: Correios, DHL, UPS, etc."
          - name: freight_value
            description: "Freight value of the sale"
          - name: ship_address_id
            description: "Foreign key of the address of the shipment (new_address)"

      - name: new_sales_details
        description: ""
        columns:
          - name: sale_id
            description: "Foreign key of the sale (new_sales)"
          - name: product_id
            description: "Foreign key of the product (new_products)"
          - name: price_per_unit
            description: "Price per unit of the product"
          - name: qty
            description: "Qty of the product that was purchased"
          - name: discount_percentage
            description: "Percentage of the discount of the product"
          - name: deleted
            description: "Flag if the item was deleted of the sale"
          
      - name: new_suppliers
        description: "Suppliers of the company. Example: Supplier A, Supplier B, etc."
        columns:
          - name: supplier_id
            description: "Primary key of the supplier"
            tests:
              - unique
              - not_null
          - name: supplier_name
            description: "Name of the supplier"
          - name: contact_person
            description: "Name of the contact person of the supplier"
          - name: phone
            description: "Phone number of the supplier"
          - name: email
            description: "Email of the supplier"