name: 'penna_airflow_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'penna_airflow_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  penna_airflow_dbt:    
    stage:
      northwind:
        schema: stage_northwind
        +materialized: table
    
    intermediate:
      schema: intermediate
      +materialized: ephemeral
    
    datamart:
      schema: marts
      +materialized: table

seeds:
  penna_airflow_dbt:
    schema: raw

snapshots:
  penna_airflow_dbt:
    northwind:
      schema: stage_northwind