version: 2

models:
  - name: int_dim_customers
    description: "Consolidated customer dimension from Northwind and ERP New System sources."
    columns:
      - name: customer_id
        description: "Primary key of the customer."
      - name: customer
        description: "Customer's company name."
      - name: customer_contact_name
        description: "Main contact person for the customer."
      - name: customer_contact_title
        description: "Title of the contact person (e.g., Sales Representative, Owner)."
      - name: customer_address
        description: "Customer's address."
      - name: customer_city
        description: "Customer's city."
      - name: customer_region
        description: "Customer's region or state."
      - name: customer_postal_code
        description: "Customer's postal code."
      - name: customer_country
        description: "Customer's country."
      - name: customer_phone
        description: "Customer's phone number."
      - name: customer_fax
        description: "Customer's fax number."
      - name: source
        description: "Source system for the record: 'northwind' or 'erp_new_system'."

  - name: int_dim_employees
    description: "Consolidated employee dimension from Northwind and ERP New System sources."
    columns:
      - name: employee_id
        description: "Primary key of the employee."
      - name: employee
        description: "Employee's full name."
      - name: employee_title
        description: "Job title of the employee."
      - name: employee_birth_date
        description: "Employee's date of birth."
      - name: employee_hire_date
        description: "Date the employee was hired."
      - name: employee_reports_to
        description: "ID of the employee's immediate supervisor."
      - name: employee_hierarchy_level
        description: "Hierarchy level of the employee."
      - name: employee_superior_level_1
        description: "Name of the top-level superior in the hierarchy."
      - name: employee_superior_level_2
        description: "Name of the second-level superior in the hierarchy."
      - name: employee_superior_level_3
        description: "Name of the third-level superior in the hierarchy."
      - name: employee_superior_level_4
        description: "Name of the fourth-level superior in the hierarchy."
      - name: hierarchy_path
        description: "Full hierarchical path from the top to this employee."
      - name: employee_source
        description: "Source system for the record: 'northwind' or 'erp_new_system'."

  - name: int_dim_products
    description: "Consolidated product dimension from Northwind and ERP New System sources."
    columns:
      - name: product_id
        description: "Primary key of the product."
      - name: product
        description: "Product name."
      - name: category_id
        description: "Foreign key to the product category."
      - name: product_category
        description: "Name of the product category."
      - name: product_category_description
        description: "Description of the product category."
      - name: supplier_id
        description: "Foreign key to the supplier."
      - name: product_supplier
        description: "Name of the supplier."
      - name: product_quantity_per_unit
        description: "Quantity per unit (e.g., 10 boxes x 20 bags)."
      - name: product_unit_price
        description: "Unit price of the product."
      - name: product_units_in_stock
        description: "Units of product in stock."
      - name: product_units_on_order
        description: "Units of product on order."
      - name: product_reorder_level
        description: "Reorder level for the product."
      - name: product_discontinued
        description: "Indicates if the product is discontinued."
      - name: product_source
        description: "Source system for the record: 'northwind' or 'erp_new_system'."

  - name: int_dim_shippers
    description: "Shipper dimension from Northwind source."
    columns:
      - name: shipper_id
        description: "Primary key of the shipper."
      - name: shipper
        description: "Name of the shipping company."
      - name: shipper_phone
        description: "Phone number of the shipping company."
      - name: shipper_source
        description: "Source system for the record: 'northwind'."

  - name: int_fact_orders
    description: "Fact table for orders, combining order and order details from Northwind and ERP New System sources."
    columns:
      - name: order_id
        description: "Primary key of the order."
      - name: customer_id
        description: "Foreign key to the customer. "
      - name: salesperson_id
        description: "Foreign key to the salesperson/employee."
      - name: order_date
        description: "Date when the order was placed."
      - name: product_id
        description: "Foreign key to the product."
      - name: unit_price
        description: "Unit price of the product in the order."
      - name: quantity
        description: "Quantity of the product in the order."
      - name: product_discount_percentage
        description: "Discount percentage applied to the product."
      - name: product_sales_revenue
        description: "Gross sales revenue for the product."
      - name: product_discount_value
        description: "Discount value for the product."
      - name: gross_revenue
        description: "Gross revenue for the order line."
      - name: net_revenue
        description: "Net revenue for the order line."
      - name: required_date
        description: "Date requested for delivery."
      - name: shipped_date
        description: "Date when the order was shipped."
      - name: shipped_flag
        description: "Indicates if the order was shipped."
      - name: delayed_flag
        description: "Indicates if the order was delivered late."
      - name: delayed_days
        description: "Number of days the delivery was delayed."
      - name: shipping_time
        description: "Total shipping time in days."
      - name: ship_via
        description: "Shipping company or method used for delivery."
      - name: ship_name
        description: "Name of the shipping location."
      - name: ship_address
        description: "Street address of the shipping location."
      - name: ship_city
        description: "City of the shipping location."
      - name: ship_region
        description: "Region or state of the shipping location."
      - name: ship_postal_code
        description: "Postal code of the shipping location."
      - name: ship_country
        description: "Country of the shipping location."
