version: 2

models:
  - name: stg_categories
    description: "Product categories. e.g.: beverages, condiments, dairy products, etc."
    columns:
      - name: category_id
        description: "Primary key of the category"
      - name: category_name
        description: "Name of the category"
      - name: description
        description: "Detailed description of the category"
      - name: picture
        description: "Should be the picture of the category but it is empty"

  - name: stg_customers
    description: "Customers. e.g.: Cactus Comidas para llevar, Rancho grande, etc."
    columns:
      - name: customer_id
        description: "Primary key of the customer"
      - name: company_name
        description: "Name of the company"
      - name: contact_name
        description: "Name of the contact person"
      - name: contact_title
        description: "Title of the contact person. e.g.: Sales Representative, Sales Agent, Owner, etc."
      - name: address
        description: "Address of the company. Not standard (written text)."
      - name: city
        description: "City of the company. They looks like the same names everytime."
      - name: region
        description: "Region of the company (in some cases it is the UF of the state other cases it is full name of state). e.g: RJ, SP, Québec, etc. There are some null values."
      - name: postal_code
        description: "Postal code of the company"
      - name: country
        description: "Country of the company"
      - name: phone
        description: "Phone of the company"
      - name: fax
        description: "Fax of the company"

  - name: stg_employee_territories
    description: "Relationship between employees and territories"
    columns:
      - name: employee_id
        description: "Foreign key of the employee"
      - name: territory_id
        description: "Foreign key of the territory"

  - name: stg_employees
    description: "Employees. e.g.: Nancy Davolio, Andrew Fuller, Janet Leverling, etc."
    columns:
      - name: employee_id
        description: "Primary key of the employee"
      - name: last_name
        description: "Last name of the employee"
      - name: first_name
        description: "First name of the employee"
      - name: title
        description: "Title of the employee. e.g.: Sales Representative, Sales Agent, Owner, etc."
      - name: title_of_courtesy
        description: "Title of courtesy of the employee. e.g.: Ms., Mr., Mrs., Dr., etc."
      - name: birth_date
        description: "Birth date of the employee"
      - name: hire_date
        description: "Hire date of the employee"
      - name: address
        description: "Address of the employee. Not standard (written text)."
      - name: city
        description: "City of the employee. They looks like the same names everytime."
      - name: region
        description: "Region of the employee (state). There are some null values."
      - name: postal_code
        description: "Postal code of the employee"
      - name: country
        description: "Country of the employee"
      - name: home_phone
        description: "Home phone of the employee"
      - name: extension
        description: "Extension of the employee"
      - name: notes
        description: "Notes of the employee"
      - name: reports_to
        description: "Reports to of the employee"

  - name: stg_employee_hierarchy
    description: "Employee hierarchy generated recursively from stg_employees."
    columns:
      - name: employee_id
        description: "Primary key of the employee"
      - name: reports_to
        description: "Id of the the person this employee reports to. This is related to employee_id at this table (recursive relationship)"
      - name: employee_name
        description: "Name of the employee"
      - name: hierarchy_path
        description: "Path of the employee from the higher hierarchy to the lower. e.g.: Nancy Davolio -> Andrew Fuller -> Janet Leverling"
      - name: hierarchy_level
        description: "Level of the employee in the hierarchy. e.g.: Nancy Davolio is level 1, Andrew Fuller is level 2, Janet Leverling is level 3"
  - name: stg_order_details
    description: "Detail of each order like which products, unit price, qty, was bought, etc."
    columns:
      - name: order_id
        description: "Foreign key of the order"
      - name: product_id
        description: "Foreign key of the product"
      - name: unit_price
        description: "Unit price of the product"
      - name: quantity
        description: "Quantity of the product"
      - name: discount
        description: "Discount of the product"

  - name: stg_orders
    description: "Order information like the customer, sales person, date, etc."
    columns:
      - name: order_id
        description: "Primary key of the order"
      - name: customer_id
        description: "Foreign key of the customer"
      - name: employee_id
        description: "Foreign key of the employee"
      - name: ship_via_id
        description: "Foreign key of the ship via"
      - name: order_date
        description: "Date of the order"
      - name: required_date
        description: "Required date of the order"
      - name: shipped_date
        description: "Shipped date of the order"
      - name: freight
        description: "Freight value of the order"
      - name: ship_name
        description: "Name of the ship"
      - name: ship_address
        description: "Address of the ship. Not standard (written text)."
      - name: ship_city
        description: "City of the ship. They looks like the same names everytime."
      - name: ship_region
        description: "Region of the ship (state). There are some null values."
      - name: ship_postal_code
        description: "Postal code of the ship"
      - name: ship_country
        description: "Country of the ship"

  - name: stg_products
    description: "Products. e.g.: Chai, Chang, Aniseed Syrup, etc."
    columns:
      - name: product_id
        description: "Primary key of the product"
      - name: product_name
        description: "Name of the product"
      - name: supplier_id
        description: "Foreign key of the supplier"
      - name: category_id
        description: "Foreign key of the category"
      - name: quantity_per_unit
        description: "Description of quantity per unit of the product. e.g.: 10 boxes x 20 bags, 24 - 12 oz bottles, etc."
      - name: unit_price
        description: "Unit price of the product"
      - name: units_in_stock
        description: "Units in stock of the product"
      - name: units_on_order
        description: "Units on order of the product"
      - name: reorder_level
        description: "Reorder level of the product"
      - name: discontinued
        description: "Discontinued flag of the product"

  - name: stg_region
    description: "Region information. E.g: Eastern, Western, etc."
    columns:
      - name: region_id
        description: "Primary key of the region"
      - name: region_description
        description: "Description of the region"

  - name: stg_shippers
    description: "Companies responsable for shipping. e.g.: Speedy Express, United Package, etc."
    columns:
      - name: shipper_id
        description: "Primary key of the shipper"
      - name: company_name
        description: "Name of the shipper"
      - name: phone
        description: "Phone of the shipper"

  - name: stg_suppliers
    description: "Suppliers. e.g.: Exotic Liquids, New Orleans Cajun Delights, etc."
    columns:
      - name: supplier_id
        description: "Primary key of the supplier"
      - name: company_name
        description: "Name of the supplier"
      - name: contact_name
        description: "Contact name of the supplier"
      - name: contact_title
        description: "Contact title of the supplier. e.g: Marketing Manager, Sales Representative, Owner, etc."
      - name: address
        description: "Address of the supplier. Not standard (written text)."
      - name: city
        description: "City of the supplier. They looks like the same names everytime."
      - name: region
        description: "Region of the supplier (state). There are some null values."
      - name: postal_code
        description: "Postal code of the supplier"
      - name: country
        description: "Country of the supplier"
      - name: phone
        description: "Phone of the supplier"
      - name: fax
        description: "Fax of the supplier"
      - name: homepage
        description: "Homepage of the supplier. A lot of empty values"

  - name: stg_territories
    description: "Territories (cities). e.g.: Boston, Cambridge, Orlando, etc."
    columns:
      - name: territory_id
        description: "Primary key of the territory"
      - name: territory_description
        description: "Description of the territory"
      - name: region_id
        description: "Foreign key of the region. e.g.: western, eastern, etc."

  - name: stg_us_states
    description: "United States states. e.g.: Alabama, Alaska, Arizona, etc."
    columns:
      - name: state_id
        description: "Primary key of the state"
      - name: state_name
        description: "Name of the state"
      - name: state_abbr
        description: "Abbreviation of the state"
      - name: state_region
        description: "Region of the state. e.g.: south, north, west, etc."
